OK-470 ja OK-469 Java cas client ja onr-integraatio
Opetushallitus/viestinvalityspalvelu pull request #31
Opened 2024-07-16 10:27 UTC by marjakari

Lisätty java-cas-client ja palvelutunnuksen salasana aws parameter storeen. Raportointibackendiin uusi api jonka kautta saa oppijanumerorekisterin omattiedot-rajapinnasta asiointikielen.

2024-07-16 10:54 UTC, msiukola commented on lambdat/raportointi/src/main/scala/fi/oph/viestinvalitys/raportointi/resource/OmatTiedotResource.scala
> +    val result = ONRService.apply().haeAsiointikieli("1.2.246.562.24.56298189758")
Tuohon on varmaan unohtunut kovakoodattu testiarvo 1.2.246.562.24.56298189758?

Lisäksi eikö tässä nyt instansoida uusi ONRService aina kun uusi kutsu tulee sisään? Sen voisi ehkä instansoida kertaalleen ylempänä tyyliin val onrService = ONRService.apply() ja sitten tässä vain kutsua samaa onrServiceä uudelleen (relevantilla oidilla).

2024-07-16 10:57 UTC, msiukola commented on pom.xml
> +    <java.cas.version>1.2.0-SNAPSHOT</java.cas.version>
Uusimman version 1.2.1 voisi ottaa käyttöön

2024-07-16 11:08 UTC, msiukola commented on lambdat/raportointi/src/main/scala/fi/oph/viestinvalitys/raportointi/integration/OnrService.scala
> +    try
Tämä try voisi ehkä ottaa sisäänsä myös ylläolevan?

2024-07-16 11:12 UTC, msiukola requested changes
Laitoin pari kommenttia

Tuli vielä sivuhuomiona mieleen että voisi harkita kaikkien tietojen (asiointikieli + kutsumanimi + sukunimi) palauttamista kutsujalle saman tien, kun ne kerran on käsillä? Se voi olla kyllä toki olla käytännössä tarpeetonta, mutta endpointin nimikin viittaa siihen suuntaan.

2024-07-16 11:22 UTC, msiukola commented on lambdat/raportointi/src/main/scala/fi/oph/viestinvalitys/raportointi/integration/OnrService.scala
> +      Await.result(result, Duration(2, TimeUnit.MINUTES))
Lyhyempikin timeout voisi riittää

2024-07-16 11:24 UTC, msiukola commented on lambdat/raportointi/src/main/scala/fi/oph/viestinvalitys/raportointi/integration/OnrService.scala
> +      case Left(e) => Left(new RuntimeException(s"Failed to get omat tiedot for $personOid"))
Tässä olisi tärkeää vähintään lokittaa alkuperäinen virhe, se jää nyt piiloon kun kutsujalle palautetaan uusi virhe

2024-07-16 11:27 UTC, msiukola commented on lambdat/raportointi/src/main/scala/fi/oph/viestinvalitys/raportointi/integration/ScalaCasUtil.scala
> +}
Oliko tämän tarkoitus olla käytössä jossain?

2024-07-16 12:41 UTC, marjakari commented on lambdat/raportointi/src/main/scala/fi/oph/viestinvalitys/raportointi/resource/OmatTiedotResource.scala
> +    val result = ONRService.apply().haeAsiointikieli("1.2.246.562.24.56298189758")
No hupsista, kovakoodaushan siellä, eipäs tullut katsottua tarkkaan mihin vaiheeseen jäi kun tämä tiketti jäi odottelemaan.

2024-07-17 12:50 UTC, msiukola approved these changes

2024-07-17 12:58 UTC, merged